name: gh-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Convert base_url for gh-pages
        run: sed -i '2 s/base_url = "\/"/base_url = "https:\/\/sohosai.github.io\/"/g' config.toml
      - name: Show config.toml
        run: cat config.toml
      - name: Build and Deploy Zola
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
